### ISSUE TITLE
Bug: R's .RDS files on Zenodo

### ISSUE THREAD

**Issue by shdam** [vsbuffalo/scidataflow#16]
Hey,

I recently came across `SciDataFlow` and decided to give it a go today.

I want to store .RDS files on Zenodo, as they compress well and are convenient for my use.
However, when a Zenodo entry has an .RDS file, I consistently get an error like the following:

```
$ sdf pull
Error: error decoding response body: invalid type: floating point `51.0`, expected usize at line 1 column 85

Caused by:
    invalid type: floating point `51.0`, expected usize at line 1 column 85
```

The same occurs with `sdf status --remotes` and `sdf push`.

The error can be replicated with a simple object like:
```
R
saveRDS(1, "test.rds")
```
Pushing it to Zenodo works, but then the error starts occurring.

Is this something you can help with?

Thanks for a cool tool!

Best regards,
Søren

**Comment by vsbuffalo** [comment]
Thanks Søren for your bug report! 

I am able to replicate this issue with Zenodo, but curiously the bug is not present when using Figshare as a remote repository. I am in the process of trying to figure out and correct the issue.

**Comment by vsbuffalo** [comment]
Okay after some amount of work, I have tracked down the issue. The bug is not in SciDatFlow, but an undocumented change in Zenodo's API that goes against their own spec. I have reported their issue. In case any other developers using Zenodo's API run into this same bug, I have included my email to them below for transparency/documentation. 

The correct way to address issue is for Zenodo to fix this bug. However, this may not happen in a reasonable amount of time and I want you to be able to use SciDataFlow in the meantime. To this end, I have written a shim that addresses this issue. However, at this point I will delay pushing the shim fix to crates.io, because Zenodo may fix the issue quickly and the shim may not be needed. To install the shim fix, you can use:

```
$ cargo install --git https://github.com/vsbuffalo/scidataflow.git --branch zenodo-shim
```

Let me know if this addresses your issue. I will keep this issue open in case others have this same problem. 

Bug report to Zenodo:

```
Hi Zenodo,

I am the developer of SciDataFlow (https://github.com/vsbuffalo/scidataflow), a git-like tool to manage scientific data. I use the Zenodo API to push and pull files to a remote Zenodo repository. 

Recently a user reported an issue (https://github.com/vsbuffalo/scidataflow/issues/16) and in trying to track down this bug, I believe it is originating from an undocumented API change that goes against spec. I cannot find mention of any API changes (my apologies if I have missed something) that could have caused this issue. In looking at the raw responses, the issue seems to be caused by doing a GET /api/deposit/depositions. The spec (https://developers.zenodo.org/#deposition-files) suggests that deposition "filesize" should be an integer, but I am receiving floats back (below is the raw body, which I've separated with new lines to make clear where the issue is):

[src/lib/api/zenodo.rs:552:9] &body = "[{\"id\": \"68dacda4-309b-4c63-9f39-b5dfd558bc89\", \"filename\": \"test.Rds\", 

\"filesize\": 101.0,

 \"checksum\": \"a23040e260dde1eee0730218291b9520\", \"links\": {\"self\": \"https://zenodo.org/api/deposit/depositions/10694952/files/68dacda4-309b-4c63-9f39-b5dfd558bc89\", \"download\": \"https://zenodo.org/api/records/10694952/draft/files/test.Rds/content\"}}]"

I believe this is a bug on your end. Could you please confirm this, and if so, address the issue?
```

**Comment by shdam** [comment]
Hi Vince,

Thanks a lot for the shim fix!
I had an initial problem where some local files were deleted instead of pulled when running `sdf pull --overwrite`, but now it appears to be running and working smoothly.

Thanks for the nice tool and swift updates!

Best regards,
Søren

**Comment by shdam** [comment]
Hi Vince,

Apologies for the slow reply.
It did indeed delete local files without downloading. (Un)Fortunately, I fail to replicate what happened, but this is essentially it:

```
$ sdf pull --overwrite
  [========================================] 1/1 (100%) eta 00:00:00 Fetching completed.         ⠁ [Downloaded 2 files.
 - file1.rds
 - file2.rds
Skipped 1 files. Reasons:
  Remote file is indentical to local file: 1 file
   - file3.rds
   ```
   
   ```
  $ sdf status --remotes
  [========================================] 1/1 (100%) eta 00:00:00 Fetching completed.         ⠁ [  [========================================] 3/3 (100%) eta 00:00:00 Complete.                   Project data status:
3 files local and tracked by a remote (0 files only local, 0 files only remote), 3 files total.

[inst/extdata > Zenodo]
 file1.rds       deleted, tracked      131934e7                                             exists on remote
 file2.rds      deleted, tracked      e51c9934                                             exists on remote
 file3.rds      current, tracked      7d611c97      2023-11-16  1:20PM (3 months ago)      identical remote                                    
   ```
   
Files 1 and 2 had some local changes I wanted overwritten. File 3 was identical to on remote.

My "solution" was to download the files manually, which seems to have solved any issues. Any changes are now overwritten without deleting the file.

Best regards,
Søren

**Comment by vsbuffalo** [comment]
Thanks Søren! 

I looked at the code today — I remember now, this behavior was intentional at the time to avoid doubling disk usage temporarily (and considered safe since `--overwrite` was set). But this isn't really the best behavior in hindsight. 

[14e1ccf](https://github.com/vsbuffalo/scidataflow/commit/14e1ccfa406c671fee474dc602155813ebc670b9) addresses this issue — it is available on crates.io now. This will move file `name.txt.gz` to `name.txt.gz.tmp` and then remove these temporary files once the download has completed. 

I will keep this issue open, as I have not heard back from Zenodo yet.

**Comment by vsbuffalo** [comment]
Zenodo did admit the error and fixed it. 

I will keep the shim in place as I think it does no harm. It may be removed at a later data.

Here is their email for a record of the issue.
```
Regarding your question (2) Is the filesize in bytes?   : yes, all the sizes are in bytes. The issue was in the serialization of the value, which we believe is now fixed. I.e. looking at your deposition files (https://zenodo.org/api/deposit/depositions/10694952/files):

"filesize": 101
"filesize": 4
"filesize": 24

If you have any questions, do not hesitate to contact us.


```
