### ISSUE TITLE
feat request: allow option for following symbolic links

### ISSUE THREAD

**Issue by mrvollger** [vsbuffalo/scidataflow#19]
Hi @vsbuffalo,

Right now if I try to add symbolic links outside of the directory, I get an error like:
```
sdf add results/GM12878/FDR-peaks/FDR-FIRE-peaks.bed.gz
Error: Failed to compute relative path
```
Is there any chance there could be an option to follow symbolic links like this, but when pushing and downloading, treat them like the full file is there?

My use case is linking results from a large pipeline into a directory where I am doing analysis on a subset of those results, and I want to track the subset I am using. 

Thanks,
Mitchell

**Comment by vsbuffalo** [comment]
Hi Mitchell,

Thanks for raising this issue. I have thought about adding this feature but haven't because I wasn't able to figure out the best behavior. The issue is that `sdf pull` would over write the path, not the link. That may be find, but I worry it could lead to accidental data loss. 

What is the behavior you would like SciDataFlow to have? Are these links within your project directory, or outside of it?

**Comment by mrvollger** [comment]
I had not considered this... that is a tricky problem, and now that you lay it out I am not sure there is a good solution. 

Unfortunately it is outside of my project. And on a different network volume so I cannot hard link. But really copying is not the end of the world. 

I just wanted to ask, but now I see the issue with doing it. 

Enjoying the tool!

Thanks
Mitchell
